import {
  Hero,
  Navbar,
  Popular,
  Latest,
  Subscribe,
  Testimonials,
  Footer,
} from "@/components";
import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white">
        <div className="px-10">
          <Navbar />
          <Popular />
          <Latest />
          <Subscribe />
          <Testimonials />
        </div>
        <Footer />
      </main>
    </div>
  );
}
