import {
  Hero,
  Navbar,
  Popular,
  Latest,
  Subscribe,
  Testimonials,
  Footer,
} from "@/components";
import Head from "next/head";
import Script from "next/script";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Homepage</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="bg-white">
        <div className="px-10">
          <Navbar />
          <Popular />
          <Latest />
          <Subscribe />
          <Testimonials />
        </div>
        <Footer />
        <Script
          async
          src="https://www.googletagmanager.com/gtag/js?id=G-GYHCC3V7DH"
          strategy="afterInteractive"
        />
        <Script
          id="google-tag-manager"
          strategy="afterInteractive"
          dangerouslySetInnerHTML={{
            __html: `
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());
    gtag('config', 'G-GYHCC3V7DH');
  `,
          }}
        />
      </main>
    </div>
  );
}
